name: flutter_contacts
description: Flutter plugin to read, create, update, delete and observe native contacts on Android and iOS, with vCard support, and contact permission handling
version: 1.1.1+2
homepage: https://github.com/QuisApp/flutter_contacts

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^1.0.0
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.16.5

  build_runner: ^2.1.5
  freezed: ^1.0.0
  json_serializable: ^6.0.1

flutter:
  plugin:
    platforms:
      android:
        package: co.quis.flutter_contacts
        pluginClass: FlutterContactsPlugin
      ios:
        pluginClass: FlutterContactsPlugin
